# Generated by Django 2.0.1 on 2018-01-23 20:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/images.png', upload_to=core.models.Prediction.image_path)),
                ('prediction', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
